# Generated by Django 2.0.7 on 2018-08-01 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('dob', models.CharField(blank=True, max_length=100)),
                ('hometown', models.CharField(blank=True, max_length=100)),
                ('bio', models.CharField(blank=True, max_length=350)),
                ('image', models.CharField(blank=True, max_length=250)),
                ('signup_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
