# Generated by Django 2.0.7 on 2018-08-01 20:48

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20180801_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to=profiles.models.upload_path),
        ),
    ]
